export const tagMappings: Record<string, string> = {
  js: "javascript",
  "react.js": "react js",
  reactjs: "react js",
  react: "react js",
  node: "node.js",
  nodejs: "node.js",
  next: "next.js",
  nextjs: "next.js",
  typescript: "typescript",
  ts: "typescript",
  python: "python",
  py: "python",
  css: "css",
  scss: "scss",
  sass: "scss",
  html: "html",
  mongodb: "mongodb",
  mongo: "mongodb",
  express: "express.js",
  expressjs: "express.js",
  vue: "vue.js",
  vuejs: "vue.js",
  angular: "angular",
  angularjs: "angular",
  flutter: "flutter",
  dart: "dart",
};
